### ISSUE TITLE
Flipped check mark in README example 

### ISSUE THREAD

**Issue by shahbazsyed** [Huffon/factsumm#24]
![image](https://user-images.githubusercontent.com/4356098/117971557-59b58a00-b32a-11eb-9742-07c27cfbb393.png)

Hi,
Shouldn't the ✔️ be the other way around ? The first fact is consistent with the source while the second contradicts it right ?

**Comment by Huffon** [comment]
I think both fact triples should be marked with 'x'. I just captured an figure from the original paper and this figure seems to be wrong 😅
